// ─────────────────────────────────────────────────────────────────────────────
// Sample data
// ─────────────────────────────────────────────────────────────────────────────
// Curated reference data not (yet) stored in the database. Currently the
// Singapore schools dataset that powers the School & Curriculum Navigator.

import type { MockSchool } from '@/types/models'

export const MOCK_SCHOOLS: MockSchool[] = [
  {
    id: 's1',
    school_name: 'ACS International',
    slug: 'acs-international',
    school_type: 'secondary',
    curriculum: 'IB',
    zone: 'Central',
    address: '61 Pemimpin Drive, Singapore 576154',
    description: 'Co-educational international school offering the IB Middle Years Programme (Sec 1–4) and IB Diploma Programme (Sec 5–6). Renowned for its diverse international community and strong arts & sports culture.',
    website: 'https://www.acsinternational.edu.sg',
    tuition_range: 'SGD 30,000–38,000 / yr',
    highlights: ['IB Diploma & MYP', 'Co-ed', '~2,000 students', 'Strong CCA', 'Near Bishan MRT'],
  },
  {
    id: 's2',
    school_name: 'UWC South East Asia (Dover)',
    slug: 'uwc-dover',
    school_type: 'secondary',
    curriculum: 'IB',
    zone: 'West',
    address: '1207 Dover Road, Singapore 139654',
    description: 'Part of the United World Colleges network. Offers IB PYP, MYP, and Diploma with a strong emphasis on international mindedness, peace, and sustainability. Two campuses (Dover & East).',
    website: 'https://www.uwcsea.edu.sg',
    tuition_range: 'SGD 42,000–50,000 / yr',
    highlights: ['IB World School', 'UN-affiliated UWC network', 'Activity-based learning', 'Dual campus', 'Very competitive entry'],
  },
  {
    id: 's3',
    school_name: 'Tanglin Trust School',
    slug: 'tanglin-trust',
    school_type: 'secondary',
    curriculum: 'IB',
    zone: 'West',
    address: '95 Portsdown Road, Singapore 139299',
    description: 'British-curriculum international school offering IGCSE and IB Diploma. Known for academic excellence, pastoral care, and a broad co-curricular programme in a leafy campus near Holland Village.',
    website: 'https://www.tts.edu.sg',
    tuition_range: 'SGD 35,000–45,000 / yr',
    highlights: ['British-style education', 'IGCSE + IB DP', 'Pastoral care focus', 'Strong music & drama', 'Holland Road campus'],
  },
  {
    id: 's4',
    school_name: 'Stamford American International School',
    slug: 'stamford-american',
    school_type: 'secondary',
    curriculum: 'AP',
    zone: 'North-East',
    address: '1 Woodleigh Lane, Singapore 357684',
    description: 'American curriculum school offering both the IB Diploma and Advanced Placement (AP) programmes. Large campus with world-class sports facilities. Strong college counselling for US university admission.',
    website: 'https://www.sais.edu.sg',
    tuition_range: 'SGD 38,000–48,000 / yr',
    highlights: ['IB & AP dual-track', 'US university placement', 'Olympic-sized pool', 'Near Woodleigh MRT', 'College counselling'],
  },
  {
    id: 's5',
    school_name: 'SJI International',
    slug: 'sji-international',
    school_type: 'secondary',
    curriculum: 'IB',
    zone: 'West',
    address: '2 Fort Road, Singapore 439086',
    description: 'Catholic mission school offering IGCSE and IB Diploma in a values-centred environment. Balances academic rigour with character development, service, and leadership. Smaller class sizes.',
    website: 'https://www.sji-international.com.sg',
    tuition_range: 'SGD 26,000–34,000 / yr',
    highlights: ['Values-based education', 'IGCSE + IB', 'Small class sizes', 'Strong service learning', 'Fort Road location'],
  },
  {
    id: 's6',
    school_name: 'Canadian International School',
    slug: 'canadian-international',
    school_type: 'secondary',
    curriculum: 'IB',
    zone: 'West',
    address: '7 Jurong West Street 41, Singapore 649414',
    description: 'Offers the Ontario Secondary School Diploma (OSSD) and IB Diploma. Canadian curriculum with strong STEM and arts programmes. Serves a large North American expat community.',
    website: 'https://www.cis.edu.sg',
    tuition_range: 'SGD 30,000–40,000 / yr',
    highlights: ['OSSD + IB', 'Canadian pathway', 'Strong STEM', 'Lakeside campus', 'Large expat community'],
  },
  {
    id: 's7',
    school_name: 'Raffles Institution (RI)',
    slug: 'raffles-institution',
    school_type: 'jc',
    curriculum: 'A-Level',
    zone: 'Central',
    address: '1 Raffles Institution Lane, Singapore 575987',
    description: 'Singapore\'s premier government junior college offering the Singapore-Cambridge A-Level curriculum. Highly competitive direct school admission. Alumni include presidents and prime ministers of Singapore.',
    website: 'https://www.ri.edu.sg',
    tuition_range: 'SGD 500–600 / yr (PR/SC)',
    highlights: ['Top JC in Singapore', 'Raffles Programme (IP)', 'Extremely competitive entry', 'Strong alumni network', 'Near Bishan MRT'],
  },
  {
    id: 's8',
    school_name: 'Hwa Chong Institution (HCI)',
    slug: 'hwa-chong',
    school_type: 'jc',
    curriculum: 'A-Level',
    zone: 'West',
    address: '661 Bukit Timah Road, Singapore 269734',
    description: 'Prestigious autonomous government school offering the Integrated Programme (IP) from Sec 1–JC2 and A-Levels. Strong in science, mathematics, and Mandarin. Boarding school option available.',
    website: 'https://www.hci.edu.sg',
    tuition_range: 'SGD 500–600 / yr (PR/SC)',
    highlights: ['IP (Sec–JC integrated)', 'Boarding available', 'Strong science & maths', 'Bilingual advantage', 'Near Sixth Avenue MRT'],
  },
  {
    id: 's9',
    school_name: 'National Junior College (NJC)',
    slug: 'national-junior-college',
    school_type: 'jc',
    curriculum: 'A-Level',
    zone: 'North',
    address: '37 Hillcrest Road, Singapore 288913',
    description: 'Government JC offering both Singapore A-Levels and the IB Diploma Programme — one of very few JCs offering both. Strong arts and humanities programme. Near the Rail Corridor and Upper Bukit Timah.',
    website: 'https://www.njc.edu.sg',
    tuition_range: 'SGD 500–700 / yr',
    highlights: ['A-Level & IB dual-track', 'Rare public-school IB', 'Arts-humanities strength', 'Hiking/nature nearby', 'Woodlands area'],
  },
  {
    id: 's10',
    school_name: 'Nanyang Polytechnic (NYP)',
    slug: 'nanyang-polytechnic',
    school_type: 'poly',
    curriculum: 'Local',
    zone: 'Central',
    address: '180 Ang Mo Kio Ave 8, Singapore 569830',
    description: 'One of Singapore\'s five polytechnics. Offers 3-year diploma programmes in Engineering, Business, Design, Health Sciences, and IT. Strong industry partnerships and internship placements.',
    website: 'https://www.nyp.edu.sg',
    tuition_range: 'SGD 3,000–4,500 / yr',
    highlights: ['3-year diploma', 'Strong IT & Engineering', 'Industry internships', 'Near Ang Mo Kio MRT', 'Practical hands-on focus'],
  },
  {
    id: 's11',
    school_name: 'Singapore Polytechnic (SP)',
    slug: 'singapore-polytechnic',
    school_type: 'poly',
    curriculum: 'Local',
    zone: 'South',
    address: '500 Dover Road, Singapore 139651',
    description: 'Singapore\'s oldest polytechnic. Offers diploma programmes in Engineering, Business, Hospitality, Media, and Built Environment. Known for strong alumni network and industry-ready graduates.',
    website: 'https://www.sp.edu.sg',
    tuition_range: 'SGD 3,000–4,500 / yr',
    highlights: ['Oldest poly in SG', 'Wide course range', 'Near Dover MRT', 'Strong alumni', 'Hospitality & media courses'],
  },
  {
    id: 's12',
    school_name: 'National University of Singapore (NUS)',
    slug: 'nus',
    school_type: 'university',
    curriculum: 'Local',
    zone: 'West',
    address: '21 Lower Kent Ridge Rd, Singapore 119077',
    description: 'Singapore\'s flagship university and consistently ranked Asia\'s top university. Offers undergraduate, postgraduate, and research programmes across 17 faculties. Global exchange programme with 300+ partner universities.',
    website: 'https://www.nus.edu.sg',
    tuition_range: 'SGD 17,000–22,000 / yr (international)',
    highlights: ['#1 in Asia (QS 2025)', '300+ global partners', 'Research powerhouse', 'Near Kent Ridge MRT', '37,000+ students'],
  },
  {
    id: 's13',
    school_name: 'Nanyang Technological University (NTU)',
    slug: 'ntu',
    school_type: 'university',
    curriculum: 'Local',
    zone: 'West',
    address: '50 Nanyang Ave, Singapore 639798',
    description: 'World-class research university strong in Engineering, Computer Science, and Business. NBS (business school) and EEE faculty are globally recognised. Large green campus with integrated residential colleges.',
    website: 'https://www.ntu.edu.sg',
    tuition_range: 'SGD 17,000–22,000 / yr (international)',
    highlights: ['Top 20 globally (QS)', 'Strong Engineering & CS', 'Residential colleges', 'Green campus', 'Near Boon Lay MRT'],
  },
  {
    id: 's14',
    school_name: 'EtonHouse International School (Broadrick)',
    slug: 'etonhouse-broadrick',
    school_type: 'secondary',
    curriculum: 'IB',
    zone: 'East',
    address: '72 Broadrick Road, Singapore 439501',
    description: 'International school offering the IB PYP, MYP, and Diploma. Known for inquiry-based learning, small class sizes, and strong community spirit. Located near Mountbatten in the East.',
    website: 'https://www.etonhouse.com.sg',
    tuition_range: 'SGD 24,000–32,000 / yr',
    highlights: ['IB continuum (PYP–DP)', 'Inquiry-based learning', 'Small class sizes', 'East Singapore', 'Community focus'],
  },
  {
    id: 's15',
    school_name: 'Inlingua School of Languages',
    slug: 'inlingua-singapore',
    school_type: 'language_school',
    curriculum: null,
    zone: 'Central',
    address: '583 Orchard Road, #06-03 Forum Galleria, Singapore 238884',
    description: 'International language school offering English, Mandarin, Japanese, Korean, and other language courses. Practical conversation-focused approach with flexible scheduling for international students.',
    website: 'https://www.inlingua.com.sg',
    tuition_range: 'SGD 1,200–4,000 / course',
    highlights: ['20+ languages offered', 'Flexible schedules', 'Near Orchard MRT', 'Practical focus', 'Adult & teen programmes'],
  },
]
