'use client'

import { useState } from 'react'
import { createBrowserClient } from '@/db/client'
import { useToast } from '@/components/ui/toast'
import { useLocale } from '@/components/shared/LocaleProvider'
import type { PositioningDecision } from '@/lib/positioning'
import type { ReadinessReport } from '@/lib/readiness-check'
import { planProgress, toggleDocument } from '@/lib/university-plan'
import type { ApplicationPlan } from '@/lib/university-plan'
import type { ProposedEvent } from '@/lib/application-events'
import CompareTab from './CompareTab'
import type { ProgrammeStat } from '@/lib/programme-stats'

// ── Types ─────────────────────────────────────────────────────
// Fit/readiness analysis lives in the Portfolio assessment now — this page only
// manages application logistics (requirements, deadlines, status, links).

export interface UniversityTarget {
  id: string
  name: string
  country: string
  programme: string
  deadline: string | null
  requirements: string
  notes: string
  status: 'researching' | 'applied' | 'offer' | 'rejected' | 'enrolled'
  referenceLink: string
  applicationPlan: ApplicationPlan | null
  planUpdatedAt: string | null
}

export interface ProfileDefaults {
  university: string
  programme: string
  enrollmentYear: number | null
}

export interface TargetInsight {
  positioning: PositioningDecision
  readiness: ReadinessReport
}

interface Props {
  initialTargets: UniversityTarget[]
  insights: Record<string, TargetInsight>
  programmeStats: ProgrammeStat[]
  userId: string
  profileDefaults: ProfileDefaults
}

// ── Constants ─────────────────────────────────────────────────

const STATUS_CONFIG = {
  researching: { bg: '#EBF5FF', color: '#1A56DB' },
  applied:     { bg: '#FFFBEB', color: '#B45309' },
  offer:       { bg: '#F3FAF7', color: '#057A55' },
  rejected:    { bg: '#FDF2F2', color: '#E02424' },
  enrolled:    { bg: '#F3FAF7', color: '#057A55' },
}

// ── Copy (bilingual) ──────────────────────────────────────────

const T = {
  en: {
    status: {
      researching: 'Researching', applied: 'Applied', offer: 'Offer 🎉',
      rejected: 'Rejected', enrolled: 'Enrolled ✓',
    } as Record<UniversityTarget['status'], string>,
    verdict: { reach: 'Reach', match: 'Match', safety: 'Safety' } as Record<string, string>,
    // deadlines
    noDeadline: 'No deadline set', deadlinePassed: 'Deadline passed', dueToday: 'Due today!',
    daysLeft: (n: number) => `${n}d left`,
    // add form
    addFailed: 'Could not add the university',
    addedPlanFailed: 'Added — plan generation failed',
    addedPlanFailedDesc: 'Open the card and tap "Generate plan" to retry.',
    addTitle: 'Add a target university',
    prefilledHint: 'Pre-filled from your profile — adjust if this target differs.',
    universityLabel: 'University *',
    universityPh: 'e.g. NUS, NTU, UCL',
    programmeLabel: 'Programme',
    programmePh: 'Computer Science',
    intakeYear: 'Intake year',
    autoGenerated: 'Deadlines & document checklist are generated automatically',
    generating: '— generating…',
    cancel: 'Cancel',
    adding: 'Adding…',
    buildingPlan: 'Building plan…',
    addAndBuild: '+ Add & build plan',
    // insight panel
    positioning: 'Positioning',
    readinessTitle: 'Application readiness',
    readyToSubmit: '· ✅ Ready to submit',
    stepsLeft: '· A few steps left',
    docsReady: '✓ Docs ready',
    // card
    statusLabel: 'Status',
    couldNotAddCalendar: 'Could not add to calendar',
    tryAgain: 'Please try again.',
    addedToCalendar: 'Added to calendar',
    deadlineOf: (name: string) => `${name} deadline`,
    planFailed: 'Plan generation failed',
    sourceNeedInput: 'Add a link, paste the page, or upload a file',
    couldNotReadPage: "Couldn't read that page",
    couldNotReadPageDesc: 'Paste the text or upload a screenshot/PDF instead.',
    planBuilt: 'Plan built from the official page',
    planBuiltDesc: (n: number) => `${n} proposed events — review and sync.`,
    couldNotBuildPlan: 'Could not build a plan',
    synced: 'Synced to calendar',
    syncedDesc: (added: number, skipped: number) => `Added ${added}, skipped ${skipped} (already there).`,
    couldNotSync: 'Could not sync to calendar',
    save: 'Save',
    officialWebsite: 'Official website',
    addOfficialWebsite: '+ Add official website',
    edit: 'edit',
    addDeadlineToCalendar: '📅 Add deadline to calendar',
    applicationPlan: 'Application plan',
    fromOfficialSources: '✓ from official sources',
    unverified: 'unverified — check official site',
    fromOfficialPage: '🔗 From official page',
    building: 'Building…',
    refreshPlan: '↻ Refresh plan',
    generatePlan: '✦ Generate plan',
    sourceHint: 'Paste the official deadlines/requirements page (or a link / screenshot). The assistant builds a plan from it and proposes calendar events — nothing is shared.',
    reading: 'Reading…',
    fetch: 'Fetch',
    pastePh: '…or paste the page text here',
    uploadPdf: 'Upload PDF/screenshot',
    buildFromText: 'Build plan from text',
    contributeKb: 'Also submit this official page to the knowledge base (admin-reviewed before it’s shared)',
    couldNotReadLink: 'Couldn’t read that link — paste the page text or upload a screenshot/PDF above.',
    proposedEvents: 'Proposed calendar events',
    syncN: (n: number) => `Sync ${n} to calendar`,
    generateHint: 'Generate to get the application window, every deadline, and a document checklist.',
    applicationWindow: 'Application window:',
    deadlines: 'Deadlines',
    addToCalendar: 'Add to calendar',
    documentsToPrepare: 'Documents to prepare',
    optional: ' (optional)',
    verifiedOn: (d: string) => ` · verified ${d}`,
    planGenerated: (d: string) => `Plan generated ${d}`,
    requirements: 'Requirements',
    fetching: 'Fetching…',
    fetchWithAi: '✦ Fetch with AI',
    fetchHint: 'Click “Fetch with AI” to get entry requirements, language scores, and deadlines.',
    yourNotes: 'Your notes',
    editNotes: 'Edit',
    notesPh: 'Why this uni? Personal connection, specific lab, professor…',
    noNotes: 'No notes yet.',
    removeUniversity: 'Remove university',
    // main
    pageTitle: 'Application Tracker',
    pageSubtitle: (n: number) => `${n} universities · requirements, deadlines & status`,
    addUniversity: 'Add university',
    tabTargets: '🎯 My targets',
    tabCompare: '📊 Compare programmes',
    emptyTitle: 'No universities yet',
    emptyDesc: "Add universities you're interested in and track requirements, deadlines, and your application status.",
    addFirst: '+ Add your first university',
    secOffers: '🎉 Offers & Enrolled',
    secApplied: '📬 Applied',
    secResearching: '🔍 Researching',
    secRejected: 'Universities not pursued',
  },
  zh: {
    status: {
      researching: '调研中', applied: '已申请', offer: '录取 🎉',
      rejected: '未录取', enrolled: '已入学 ✓',
    } as Record<UniversityTarget['status'], string>,
    verdict: { reach: '冲刺', match: '匹配', safety: '稳妥' } as Record<string, string>,
    // deadlines
    noDeadline: '未设截止日期', deadlinePassed: '截止日期已过', dueToday: '今天截止！',
    daysLeft: (n: number) => `还剩 ${n} 天`,
    // add form
    addFailed: '添加大学失败',
    addedPlanFailed: '已添加——计划生成失败',
    addedPlanFailedDesc: '打开卡片，点击“生成计划”重试。',
    addTitle: '添加目标大学',
    prefilledHint: '已按你的个人资料预填——如与此目标不符请调整。',
    universityLabel: '大学 *',
    universityPh: '如 NUS、NTU、UCL',
    programmeLabel: '专业',
    programmePh: '如 Computer Science',
    intakeYear: '入学年份',
    autoGenerated: '截止日期与材料清单会自动生成',
    generating: '— 生成中…',
    cancel: '取消',
    adding: '添加中…',
    buildingPlan: '生成计划中…',
    addAndBuild: '+ 添加并生成计划',
    // insight panel
    positioning: '选校定位',
    readinessTitle: '申请就绪检查',
    readyToSubmit: '· ✅ 可以提交',
    stepsLeft: '· 还差几步',
    docsReady: '✓ 材料就绪',
    // card
    statusLabel: '状态',
    couldNotAddCalendar: '无法添加到日历',
    tryAgain: '请重试。',
    addedToCalendar: '已添加到日历',
    deadlineOf: (name: string) => `${name} 截止日期`,
    planFailed: '计划生成失败',
    sourceNeedInput: '请添加链接、粘贴页面内容或上传文件',
    couldNotReadPage: '无法读取该页面',
    couldNotReadPageDesc: '请改为粘贴文本或上传截图/PDF。',
    planBuilt: '已根据官方页面生成计划',
    planBuiltDesc: (n: number) => `${n} 个建议日程——请确认后同步。`,
    couldNotBuildPlan: '无法生成计划',
    synced: '已同步到日历',
    syncedDesc: (added: number, skipped: number) => `新增 ${added} 个，跳过 ${skipped} 个（已存在）。`,
    couldNotSync: '无法同步到日历',
    save: '保存',
    officialWebsite: '官方网站',
    addOfficialWebsite: '+ 添加官方网站',
    edit: '编辑',
    addDeadlineToCalendar: '📅 将截止日期加入日历',
    applicationPlan: '申请计划',
    fromOfficialSources: '✓ 来自官方来源',
    unverified: '未经核实——请以官网为准',
    fromOfficialPage: '🔗 从官方页面导入',
    building: '生成中…',
    refreshPlan: '↻ 刷新计划',
    generatePlan: '✦ 生成计划',
    sourceHint: '粘贴官方的截止日期/申请要求页面（或链接/截图）。助手会据此生成计划并建议日历日程——内容不会对外分享。',
    reading: '读取中…',
    fetch: '抓取',
    pastePh: '…或将页面文本粘贴到这里',
    uploadPdf: '上传 PDF/截图',
    buildFromText: '从文本生成计划',
    contributeKb: '同时将该官方页面提交到知识库（经管理员审核后才会共享）',
    couldNotReadLink: '无法读取该链接——请在上方粘贴页面文本或上传截图/PDF。',
    proposedEvents: '建议的日历日程',
    syncN: (n: number) => `同步 ${n} 个到日历`,
    generateHint: '点击生成，获取申请窗口、全部截止日期和材料清单。',
    applicationWindow: '申请窗口：',
    deadlines: '截止日期',
    addToCalendar: '添加到日历',
    documentsToPrepare: '需准备的材料',
    optional: '（可选）',
    verifiedOn: (d: string) => ` · 核实于 ${d}`,
    planGenerated: (d: string) => `计划生成于 ${d}`,
    requirements: '申请要求',
    fetching: '获取中…',
    fetchWithAi: '✦ AI 获取',
    fetchHint: '点击“AI 获取”，获取入学要求、语言成绩和截止日期。',
    yourNotes: '我的笔记',
    editNotes: '编辑',
    notesPh: '为什么选这所大学？个人渊源、特定实验室、教授……',
    noNotes: '暂无笔记。',
    removeUniversity: '移除大学',
    // main
    pageTitle: '大学申请',
    pageSubtitle: (n: number) => `${n} 所大学 · 申请要求、截止日期与状态`,
    addUniversity: '添加大学',
    tabTargets: '🎯 我的目标',
    tabCompare: '📊 项目对比',
    emptyTitle: '还没有添加大学',
    emptyDesc: '添加你感兴趣的大学，追踪申请要求、截止日期和申请状态。',
    addFirst: '+ 添加第一所大学',
    secOffers: '🎉 录取与入学',
    secApplied: '📬 已申请',
    secResearching: '🔍 调研中',
    secRejected: '未继续申请的大学',
  },
}

type Dict = (typeof T)[keyof typeof T]

const COUNTRY_EMOJI: Record<string, string> = {
  'UK': '🇬🇧', 'United Kingdom': '🇬🇧',
  'US': '🇺🇸', 'USA': '🇺🇸', 'United States': '🇺🇸',
  'Singapore': '🇸🇬', 'SG': '🇸🇬',
  'Australia': '🇦🇺', 'AU': '🇦🇺',
  'Canada': '🇨🇦', 'CA': '🇨🇦',
  'Netherlands': '🇳🇱', 'Germany': '🇩🇪',
  'Hong Kong': '🇭🇰', 'Japan': '🇯🇵',
}

function countryFlag(country: string) {
  return COUNTRY_EMOJI[country] ?? '🌏'
}

function daysUntil(dateStr: string | null, t: Dict): { text: string; urgent: boolean } {
  if (!dateStr) return { text: t.noDeadline, urgent: false }
  const diff = Math.ceil((new Date(dateStr).getTime() - Date.now()) / 86400000)
  if (diff < 0)   return { text: t.deadlinePassed, urgent: true }
  if (diff === 0) return { text: t.dueToday, urgent: true }
  if (diff <= 30) return { text: t.daysLeft(diff), urgent: true }
  if (diff <= 90) return { text: t.daysLeft(diff), urgent: false }
  return { text: t.daysLeft(diff), urgent: false }
}

// ── Add University Form ───────────────────────────────────────
// Three fields only — school, programme, intake year — prefilled from the
// student's profile. Deadlines/requirements come from the generated plan,
// not manual entry.

function AddForm({ defaults, onAdd, onCancel }: {
  defaults: ProfileDefaults
  onAdd: (u: UniversityTarget) => void
  onCancel: () => void
}) {
  const currentYear = new Date().getFullYear()
  const [uniName, setUniName] = useState(defaults.university)
  const [programme, setProg]  = useState(defaults.programme)
  const [year, setYear]       = useState(defaults.enrollmentYear ?? currentYear + 1)
  const [phase, setPhase]     = useState<'idle' | 'saving' | 'planning'>('idle')
  const supabase = createBrowserClient()
  const toast = useToast()
  const locale = useLocale()
  const t = T[locale]

  const prefilled = Boolean(defaults.university || defaults.programme)
  const years = Array.from({ length: 7 }, (_, i) => currentYear + i)

  async function submit(e: React.FormEvent) {
    e.preventDefault()
    if (!uniName.trim() || phase !== 'idle') return
    setPhase('saving')
    const { data, error } = await supabase
      .from('university_targets')
      .insert({
        name: uniName.trim(),
        programme: programme.trim(),
        country: '',
        requirements: '',
        notes: '',
        reference_link: '',
        status: 'researching',
      })
      .select('id')
      .single()
    if (error || !data) {
      setPhase('idle')
      toast({ title: t.addFailed, variant: 'error' })
      return
    }

    // Generate the plan immediately — this is the assistant's whole point.
    setPhase('planning')
    let plan: ApplicationPlan | null = null
    let planUpdatedAt: string | null = null
    try {
      const res = await fetch('/api/universities/plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ targetId: data.id }),
      })
      if (res.ok) {
        const json = await res.json()
        plan = json.plan
        planUpdatedAt = json.planUpdatedAt
      }
    } catch { /* plan can be regenerated from the card */ }

    onAdd({
      id: data.id,
      name: uniName.trim(),
      country: '',
      programme: programme.trim(),
      deadline: null,
      requirements: '',
      notes: '',
      status: 'researching',
      referenceLink: '',
      applicationPlan: plan,
      planUpdatedAt,
    })
    if (!plan) toast({ title: t.addedPlanFailed, description: t.addedPlanFailedDesc, variant: 'error' })
  }

  const cls = "w-full px-3 py-2.5 border border-[var(--border)] rounded-[8px] text-[13px] bg-white text-[var(--t900)] focus:outline-none focus:border-[var(--blue)] placeholder:text-[var(--t300)]"

  return (
    <form onSubmit={submit} className="bg-[var(--blue-50)] border border-[var(--blue-100)] rounded-[12px] p-5 mb-5 flex flex-col gap-3">
      <div className="font-display font-bold text-[13px] text-[var(--blue)]">{t.addTitle}</div>
      {prefilled && (
        <div className="text-[11px] text-[var(--t500)]">{t.prefilledHint}</div>
      )}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        <div>
          <label className="block text-[11px] font-semibold text-[var(--t700)] mb-1">{t.universityLabel}</label>
          <input value={uniName} onChange={e => setUniName(e.target.value)} placeholder={t.universityPh} className={cls} required />
        </div>
        <div>
          <label className="block text-[11px] font-semibold text-[var(--t700)] mb-1">{t.programmeLabel}</label>
          <input value={programme} onChange={e => setProg(e.target.value)} placeholder={t.programmePh} className={cls} />
        </div>
        <div>
          <label className="block text-[11px] font-semibold text-[var(--t700)] mb-1">{t.intakeYear}</label>
          <select value={year} onChange={e => setYear(Number(e.target.value))} className={cls}>
            {years.map(y => <option key={y} value={y}>{y}</option>)}
          </select>
        </div>
      </div>
      <div className="flex items-center justify-between pt-1">
        <div className="text-[11px] text-[var(--t400)]">
          {t.autoGenerated}{' '}
          {phase === 'planning' && <span className="font-semibold text-[var(--blue)]">{t.generating}</span>}
        </div>
        <div className="flex gap-2">
          <button type="button" onClick={onCancel} className="px-4 py-2 rounded-[7px] text-[12px] font-semibold text-[var(--t500)] hover:bg-white transition">{t.cancel}</button>
          <button type="submit" disabled={phase !== 'idle'} className="px-4 py-2 rounded-[7px] text-[12px] font-semibold bg-[var(--blue)] text-white hover:bg-[var(--blue-h)] disabled:opacity-50 transition">
            {phase === 'saving' ? t.adding : phase === 'planning' ? t.buildingPlan : t.addAndBuild}
          </button>
        </div>
      </div>
    </form>
  )
}

// ── University Card ───────────────────────────────────────────

const VERDICT_STYLE: Record<string, { background: string; color: string }> = {
  reach:  { background: '#FDF2F2', color: '#E02424' },
  match:  { background: '#EBF5FF', color: '#1A56DB' },
  safety: { background: '#F3FAF7', color: '#057A55' },
}
const READINESS_ICON: Record<string, string> = { ok: '✅', warning: '⚠️', missing: '❌' }

// 定位 + 就绪检查 panel — everything here is computed server-side from verified
// cases and the student's own records; refreshing the page recomputes it.
function InsightPanel({ insight }: { insight: TargetInsight }) {
  const { positioning, readiness } = insight
  const locale = useLocale()
  const t = T[locale]
  return (
    <div className="rounded-[10px] border border-[var(--border)] bg-[var(--bg)] p-3 space-y-3">
      <div>
        <div className="text-[11px] font-semibold text-[var(--t500)] mb-1.5 uppercase tracking-wider">{t.positioning}</div>
        {positioning.verdict === 'insufficient_data' ? (
          <div className="text-[12px] text-[var(--t500)]">{positioning.evidence[0]}</div>
        ) : (
          <div className="flex items-start gap-2 flex-wrap">
            <span className="inline-flex items-center px-2 py-0.5 rounded-[5px] text-[11px] font-bold"
              style={VERDICT_STYLE[positioning.verdict]}>
              {t.verdict[positioning.verdict]}
            </span>
            <div className="text-[12px] text-[var(--t500)] leading-relaxed">
              {positioning.evidence.map(e => <div key={e}>{e}</div>)}
            </div>
          </div>
        )}
      </div>
      <div>
        <div className="text-[11px] font-semibold text-[var(--t500)] mb-1.5 uppercase tracking-wider">
          {t.readinessTitle} {readiness.ready ? t.readyToSubmit : t.stepsLeft}
        </div>
        <div className="space-y-1">
          {readiness.items.map(item => (
            <div key={item.id} className="flex items-start gap-1.5 text-[12px]">
              <span className="flex-shrink-0">{READINESS_ICON[item.status]}</span>
              <span className="text-[var(--t700)] font-medium">{item.label}</span>
              {item.detail && <span className="text-[var(--t400)]">— {item.detail}</span>}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

function UniversityCard({
  target, insight, userId, onDelete, onUpdate,
}: {
  target: UniversityTarget
  insight?: TargetInsight
  userId: string
  onDelete: (id: string) => void
  onUpdate: (id: string, patch: Partial<UniversityTarget>) => void
}) {
  const [expanded, setExpanded]   = useState(false)
  const [fetching, setFetching]   = useState(false)
  const [editNotes, setEditNotes] = useState(false)
  const [notesVal, setNotesVal]   = useState(target.notes)
  const [editLink, setEditLink]   = useState(false)
  const [linkVal, setLinkVal]     = useState(target.referenceLink)
  const [planLoading, setPlanLoading] = useState(false)
  // "From the official page" → plan + adoptable events.
  const [showSource, setShowSource] = useState(false)
  const [sourceUrl, setSourceUrl] = useState('')
  const [pastedText, setPastedText] = useState('')
  const [sourceBusy, setSourceBusy] = useState(false)
  const [needsManual, setNeedsManual] = useState(false)
  const [contributeKb, setContributeKb] = useState(false)
  const [proposed, setProposed] = useState<ProposedEvent[]>([])
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const supabase = createBrowserClient()
  const toast = useToast()
  const locale = useLocale()
  const t = T[locale]
  const plan = target.applicationPlan
  const progress = plan ? planProgress(plan) : null

  const sc = STATUS_CONFIG[target.status]
  const dl = daysUntil(target.deadline, t)

  async function handleFetchReqs() {
    setFetching(true)
    setExpanded(true)
    const res = await fetch('/api/universities/requirements', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: target.name, programme: target.programme, country: target.country }),
    })
    if (res.ok) {
      const json = await res.json() as { requirements: string }
      await supabase.from('university_targets').update({ requirements: json.requirements }).eq('id', target.id)
      onUpdate(target.id, { requirements: json.requirements })
    }
    setFetching(false)
  }

  async function handleStatusChange(status: UniversityTarget['status']) {
    await supabase.from('university_targets').update({ status }).eq('id', target.id)
    onUpdate(target.id, { status })
  }

  async function handleSaveNotes() {
    await supabase.from('university_targets').update({ notes: notesVal }).eq('id', target.id)
    onUpdate(target.id, { notes: notesVal })
    setEditNotes(false)
  }

  async function handleDelete() {
    await supabase.from('university_targets').delete().eq('id', target.id)
    onDelete(target.id)
  }

  async function handleSaveLink() {
    const v = linkVal.trim()
    await supabase.from('university_targets').update({ reference_link: v }).eq('id', target.id)
    onUpdate(target.id, { referenceLink: v })
    setEditLink(false)
  }

  async function handleAddDeadlineToCalendar() {
    if (!target.deadline) return
    const { error } = await supabase.from('calendar_events').insert({
      student_id: userId,
      title:      `${target.name} application deadline`,
      event_date: target.deadline,
      type:       'application',
      source:     'manual',
      notes:      target.programme || null,
    })
    toast(error
      ? { title: t.couldNotAddCalendar, description: t.tryAgain, variant: 'error' }
      : { title: t.addedToCalendar, description: t.deadlineOf(target.name), variant: 'success' })
  }

  async function handleGeneratePlan() {
    setPlanLoading(true)
    try {
      const res = await fetch('/api/universities/plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ targetId: target.id }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error)
      onUpdate(target.id, { applicationPlan: json.plan, planUpdatedAt: json.planUpdatedAt })
    } catch {
      toast({ title: t.planFailed, description: t.tryAgain, variant: 'error' })
    } finally {
      setPlanLoading(false)
    }
  }

  async function handleFromSource(file?: File) {
    if (!sourceUrl.trim() && !pastedText.trim() && !file) {
      toast({ title: t.sourceNeedInput, variant: 'error' })
      return
    }
    setSourceBusy(true)
    setNeedsManual(false)
    try {
      const form = new FormData()
      form.append('targetId', target.id)
      if (sourceUrl.trim()) form.append('url', sourceUrl.trim())
      if (pastedText.trim()) form.append('pastedText', pastedText.trim())
      if (file) form.append('file', file)
      if (contributeKb) form.append('contribute', '1')
      const res = await fetch('/api/universities/plan/from-source', { method: 'POST', body: form })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error)
      if (json.needsManualInput) {
        setNeedsManual(true)
        toast({ title: t.couldNotReadPage, description: t.couldNotReadPageDesc, variant: 'error' })
        return
      }
      onUpdate(target.id, { applicationPlan: json.plan, planUpdatedAt: json.planUpdatedAt })
      const events: ProposedEvent[] = json.proposedEvents ?? []
      setProposed(events)
      setSelected(new Set(events.map((e) => `${e.date}|${e.title}`)))
      toast({ title: t.planBuilt, description: t.planBuiltDesc(events.length) })
    } catch (e) {
      toast({ title: t.couldNotBuildPlan, description: e instanceof Error ? e.message : undefined, variant: 'error' })
    } finally {
      setSourceBusy(false)
    }
  }

  async function handleSyncEvents() {
    const events = proposed.filter((e) => selected.has(`${e.date}|${e.title}`))
    if (events.length === 0) return
    try {
      const res = await fetch('/api/calendar/events', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ events }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error)
      toast({ title: t.synced, description: t.syncedDesc(json.added, json.skipped), variant: 'success' })
      setProposed([])
    } catch {
      toast({ title: t.couldNotSync, variant: 'error' })
    }
  }

  async function handleToggleDocument(docId: string) {
    if (!target.applicationPlan) return
    const next = toggleDocument(target.applicationPlan, docId)
    onUpdate(target.id, { applicationPlan: next }) // optimistic
    const { error } = await supabase
      .from('university_targets')
      .update({ application_plan: next })
      .eq('id', target.id)
    if (error) onUpdate(target.id, { applicationPlan: target.applicationPlan })
  }

  async function handleAddPlanDeadline(date: string, title: string) {
    const { error } = await supabase.from('calendar_events').insert({
      student_id: userId,
      title:      `${target.name}: ${title}`,
      event_date: date,
      type:       'application',
      source:     'manual',
      notes:      target.programme || null,
    })
    toast(error
      ? { title: t.couldNotAddCalendar, variant: 'error' }
      : { title: t.addedToCalendar, description: `${title} · ${date}`, variant: 'success' })
  }

  return (
    <div className="bg-white border border-[var(--border)] rounded-[12px] overflow-hidden transition-shadow hover:shadow-[0_2px_8px_rgba(0,0,0,0.06)]">
      {/* Card header */}
      <div
        className="flex items-start gap-3 px-4 py-4 cursor-pointer select-none"
        onClick={() => setExpanded(v => !v)}
      >
        {/* Country flag */}
        <div className="text-[28px] leading-none flex-shrink-0 mt-0.5">
          {countryFlag(target.country)}
        </div>

        <div className="flex-1 min-w-0">
          <div className="font-display font-bold text-[15px] text-[var(--t900)] leading-tight">{target.name}</div>
          {target.programme && (
            <div className="text-[12px] text-[var(--t500)] mt-0.5 truncate">{target.programme}</div>
          )}
          <div className="flex items-center gap-2 mt-2 flex-wrap">
            <span className="inline-flex items-center px-2 py-0.5 rounded-[5px] text-[10px] font-semibold"
              style={{ background: sc.bg, color: sc.color }}>{t.status[target.status]}</span>
            {insight && insight.positioning.verdict !== 'insufficient_data' && (
              <span className="inline-flex items-center px-2 py-0.5 rounded-[5px] text-[10px] font-semibold"
                style={VERDICT_STYLE[insight.positioning.verdict]}>
                {t.verdict[insight.positioning.verdict]}
              </span>
            )}
            {insight?.readiness.ready && (target.status === 'researching' || target.status === 'applied') && (
              <span className="inline-flex items-center px-2 py-0.5 rounded-[5px] text-[10px] font-semibold bg-[#F3FAF7] text-[#057A55]">
                {t.docsReady}
              </span>
            )}
            {target.deadline && (
              <span className="text-[11px] font-medium"
                style={{ color: dl.urgent ? 'var(--red)' : 'var(--t400)' }}>
                📅 {target.deadline} · {dl.text}
              </span>
            )}
          </div>
        </div>

        {/* Expand chevron */}
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--t300)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"
          style={{ transform: expanded ? 'rotate(180deg)' : 'none', transition: 'transform .2s', flexShrink: 0, marginTop: 4 }}>
          <path d="M6 9l6 6 6-6"/>
        </svg>
      </div>

      {/* Expanded detail */}
      {expanded && (
        <div className="border-t border-[var(--border)] px-4 pb-4 pt-3 space-y-3">

          {/* 定位 + 就绪检查 — server-computed from verified cases + your own data */}
          {insight && <InsightPanel insight={insight} />}

          {/* Status selector */}
          <div>
            <div className="text-[11px] font-semibold text-[var(--t500)] mb-1.5 uppercase tracking-wider">{t.statusLabel}</div>
            <div className="flex gap-1.5 flex-wrap">
              {(Object.keys(STATUS_CONFIG) as UniversityTarget['status'][]).map(s => (
                <button
                  key={s}
                  onClick={() => handleStatusChange(s)}
                  className="px-2.5 py-1 rounded-[6px] text-[11px] font-semibold transition border"
                  style={{
                    background:   target.status === s ? STATUS_CONFIG[s].bg : 'transparent',
                    color:        target.status === s ? STATUS_CONFIG[s].color : 'var(--t400)',
                    borderColor:  target.status === s ? STATUS_CONFIG[s].color + '44' : 'var(--border)',
                  }}
                >
                  {t.status[s]}
                </button>
              ))}
            </div>
          </div>

          {/* Official website + deadline → calendar */}
          <div className="flex flex-wrap items-center gap-2">
            {editLink ? (
              <div className="flex items-center gap-2 flex-1 min-w-[220px]">
                <input
                  value={linkVal}
                  onChange={e => setLinkVal(e.target.value)}
                  placeholder="https://official-website…"
                  className="flex-1 px-2.5 py-1.5 border border-[var(--border)] rounded-[6px] text-[12px] focus:outline-none focus:border-[var(--blue)]"
                />
                <button onClick={handleSaveLink} className="text-[11px] font-semibold text-[var(--blue)]">{t.save}</button>
                <button onClick={() => { setEditLink(false); setLinkVal(target.referenceLink) }} className="text-[11px] font-semibold text-[var(--t400)]">{t.cancel}</button>
              </div>
            ) : target.referenceLink ? (
              <a href={target.referenceLink} target="_blank" rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 text-[12px] font-semibold text-[var(--blue)] hover:underline">
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10 13a5 5 0 0 0 7.07 0l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.07 0l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>
                {t.officialWebsite}
              </a>
            ) : (
              <button onClick={() => setEditLink(true)} className="text-[12px] text-[var(--t400)] hover:text-[var(--blue)] transition">{t.addOfficialWebsite}</button>
            )}
            {target.referenceLink && !editLink && (
              <button onClick={() => setEditLink(true)} className="text-[11px] text-[var(--t300)] hover:underline">{t.edit}</button>
            )}
            {target.deadline && (
              <button onClick={handleAddDeadlineToCalendar}
                className="ml-auto inline-flex items-center gap-1 text-[11px] font-semibold px-2.5 py-1 rounded-[6px] border border-[var(--border)] text-[var(--t700)] hover:bg-[var(--bg)] transition">
                {t.addDeadlineToCalendar}
              </button>
            )}
          </div>

          {/* Application plan: window, deadlines, document checklist, sources */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <div className="text-[11px] font-semibold text-[var(--t500)] uppercase tracking-wider">
                {t.applicationPlan}
                {plan && (plan.verified
                  ? <span className="ml-2 normal-case tracking-normal font-semibold text-[10px] px-1.5 py-0.5 rounded bg-[var(--green-50)] text-[var(--green)]">{t.fromOfficialSources}</span>
                  : <span className="ml-2 normal-case tracking-normal font-semibold text-[10px] px-1.5 py-0.5 rounded bg-[var(--amber-50)] text-[var(--amber)]">{t.unverified}</span>
                )}
              </div>
              <div className="flex items-center gap-1.5">
                <button
                  onClick={() => setShowSource((s) => !s)}
                  className="text-[11px] font-semibold px-2.5 py-1 rounded-[6px] border border-[var(--border)] text-[var(--t500)] hover:border-[var(--blue)] transition"
                >
                  {t.fromOfficialPage}
                </button>
                <button
                  onClick={handleGeneratePlan}
                  disabled={planLoading}
                  className="inline-flex items-center gap-1 text-[11px] font-semibold px-2.5 py-1 rounded-[6px] bg-[var(--blue-50)] text-[var(--blue)] hover:bg-[var(--blue-100)] disabled:opacity-50 transition"
                >
                  {planLoading ? t.building : plan ? t.refreshPlan : t.generatePlan}
                </button>
              </div>
            </div>

            {showSource && (
              <div className="mb-3 rounded-[8px] border border-[var(--border)] p-3 space-y-2">
                <p className="text-[11px] text-[var(--t500)]">
                  {t.sourceHint}
                </p>
                <div className="flex gap-1.5">
                  <input
                    value={sourceUrl}
                    onChange={(e) => setSourceUrl(e.target.value)}
                    placeholder="https://nus.edu.sg/oam/…"
                    className="flex-1 px-2.5 py-1.5 border border-[var(--border)] rounded-[6px] text-[12px] bg-white"
                  />
                  <button onClick={() => handleFromSource()} disabled={sourceBusy} className="text-[12px] font-semibold px-3 py-1.5 rounded-[6px] bg-[var(--blue)] text-white disabled:opacity-50">
                    {sourceBusy ? t.reading : t.fetch}
                  </button>
                </div>
                <textarea
                  value={pastedText}
                  onChange={(e) => setPastedText(e.target.value)}
                  rows={3}
                  placeholder={t.pastePh}
                  className="w-full px-2.5 py-1.5 border border-[var(--border)] rounded-[6px] text-[12px] bg-white"
                />
                <div className="flex items-center gap-2">
                  <label className="text-[12px] font-semibold px-2.5 py-1.5 rounded-[6px] border border-[var(--border)] text-[var(--t500)] cursor-pointer hover:border-[var(--blue)]">
                    {t.uploadPdf}
                    <input type="file" accept="application/pdf,image/*,.txt" className="hidden"
                      onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFromSource(f); e.target.value = '' }} />
                  </label>
                  <button onClick={() => handleFromSource()} disabled={sourceBusy} className="text-[12px] font-semibold px-3 py-1.5 rounded-[6px] bg-[var(--blue-50)] text-[var(--blue)] disabled:opacity-50">
                    {t.buildFromText}
                  </button>
                </div>
                <label className="flex items-center gap-1.5 text-[11px] text-[var(--t500)]">
                  <input type="checkbox" checked={contributeKb} onChange={(e) => setContributeKb(e.target.checked)} />
                  {t.contributeKb}
                </label>
                {needsManual && (
                  <p className="text-[11px] text-[var(--amber)]">{t.couldNotReadLink}</p>
                )}
              </div>
            )}

            {proposed.length > 0 && (
              <div className="mb-3 rounded-[8px] border border-[var(--blue)] bg-[var(--blue-50)] p-3">
                <div className="text-[11px] font-semibold text-[var(--t700)] mb-1.5">{t.proposedEvents}</div>
                <div className="space-y-1">
                  {proposed.map((e) => {
                    const key = `${e.date}|${e.title}`
                    return (
                      <label key={key} className="flex items-center gap-2 text-[12px] text-[var(--t700)]">
                        <input
                          type="checkbox"
                          checked={selected.has(key)}
                          onChange={(ev) => setSelected((s) => { const n = new Set(s); if (ev.target.checked) n.add(key); else n.delete(key); return n })}
                        />
                        <span className="font-semibold">{e.date}</span> · {e.title}
                      </label>
                    )
                  })}
                </div>
                <button onClick={handleSyncEvents} disabled={selected.size === 0} className="mt-2 text-[12px] font-semibold px-3 py-1.5 rounded-[6px] bg-[var(--blue)] text-white disabled:opacity-50">
                  {t.syncN(selected.size)}
                </button>
              </div>
            )}

            {!plan && !planLoading && (
              <div className="text-[12px] text-[var(--t300)] italic py-1">
                {t.generateHint}
              </div>
            )}

            {plan && (
              <div className="space-y-3">
                {plan.applicationWindow && (
                  <div className="text-[12px] text-[var(--t700)] bg-[var(--bg)] rounded-[8px] px-3 py-2">
                    <span className="font-semibold">{t.applicationWindow}</span>{' '}
                    {plan.applicationWindow.opens} → {plan.applicationWindow.closes}
                  </div>
                )}

                {plan.deadlines.length > 0 && (
                  <div>
                    <div className="text-[11px] font-semibold text-[var(--t500)] mb-1">{t.deadlines}</div>
                    <div className="space-y-1">
                      {plan.deadlines.map((d, i) => {
                        const dd = daysUntil(d.date, t)
                        return (
                          <div key={i} className="flex items-center gap-2 text-[12px]">
                            <span className="font-medium text-[var(--t700)] whitespace-nowrap">{d.date}</span>
                            <span className="text-[var(--t500)] flex-1 min-w-0 truncate" title={d.description}>{d.title}</span>
                            <span className="text-[11px] whitespace-nowrap" style={{ color: dd.urgent ? 'var(--red)' : 'var(--t300)' }}>{dd.text}</span>
                            <button
                              onClick={() => handleAddPlanDeadline(d.date, d.title)}
                              title={t.addToCalendar}
                              className="text-[11px] px-1.5 py-0.5 rounded border border-[var(--border)] text-[var(--t500)] hover:bg-[var(--bg)] transition"
                            >📅</button>
                          </div>
                        )
                      })}
                    </div>
                  </div>
                )}

                {plan.documents.length > 0 && progress && (
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <div className="text-[11px] font-semibold text-[var(--t500)]">{t.documentsToPrepare}</div>
                      <div className="text-[11px] text-[var(--t400)]">{progress.done}/{progress.total}</div>
                    </div>
                    <div className="h-1.5 bg-[var(--bg)] rounded-full overflow-hidden mb-2">
                      <div className="h-full bg-[var(--green)] transition-all" style={{ width: `${progress.pct}%` }} />
                    </div>
                    <div className="space-y-1">
                      {plan.documents.map((d) => (
                        <label key={d.id} className="flex items-start gap-2 text-[12px] cursor-pointer group">
                          <input
                            type="checkbox"
                            checked={d.done}
                            onChange={() => handleToggleDocument(d.id)}
                            className="mt-0.5"
                          />
                          <span className={d.done ? 'line-through text-[var(--t300)]' : 'text-[var(--t700)] group-hover:text-[var(--t900)]'}>
                            {d.title}
                            {!d.required && <span className="text-[var(--t300)]">{t.optional}</span>}
                          </span>
                        </label>
                      ))}
                    </div>
                  </div>
                )}

                {(plan.notes || plan.sources.length > 0 || target.planUpdatedAt) && (
                  <div className="text-[11px] text-[var(--t400)] space-y-1 pt-1 border-t border-[var(--border)]">
                    {plan.notes && <div>ⓘ {plan.notes}</div>}
                    {plan.sources.map((s) => (
                      <a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer" className="block text-[var(--blue)] hover:underline truncate">
                        {s.title ?? s.url}{s.lastVerified ? t.verifiedOn(s.lastVerified) : ''}
                      </a>
                    ))}
                    {target.planUpdatedAt && <div>{t.planGenerated(target.planUpdatedAt.slice(0, 10))}</div>}
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Requirements */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <div className="text-[11px] font-semibold text-[var(--t500)] uppercase tracking-wider">{t.requirements}</div>
              <button
                onClick={handleFetchReqs}
                disabled={fetching}
                className="inline-flex items-center gap-1 text-[11px] font-semibold px-2.5 py-1 rounded-[6px] bg-[var(--blue-50)] text-[var(--blue)] hover:bg-[var(--blue-100)] disabled:opacity-50 transition"
              >
                {fetching ? (
                  <>
                    <svg className="animate-spin w-3 h-3" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z"/>
                    </svg>
                    {t.fetching}
                  </>
                ) : t.fetchWithAi}
              </button>
            </div>
            {target.requirements ? (
              <div className="text-[12px] text-[var(--t700)] leading-[1.7] bg-[var(--bg)] rounded-[8px] px-3 py-3 whitespace-pre-wrap">
                {target.requirements}
              </div>
            ) : (
              <div className="text-[12px] text-[var(--t300)] italic py-2">
                {t.fetchHint}
              </div>
            )}
          </div>

          {/* Notes */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <div className="text-[11px] font-semibold text-[var(--t500)] uppercase tracking-wider">{t.yourNotes}</div>
              {!editNotes && (
                <button onClick={() => setEditNotes(true)} className="text-[11px] text-[var(--blue)] font-semibold hover:underline">{t.editNotes}</button>
              )}
            </div>
            {editNotes ? (
              <div className="flex flex-col gap-2">
                <textarea
                  value={notesVal}
                  onChange={e => setNotesVal(e.target.value)}
                  rows={3}
                  placeholder={t.notesPh}
                  className="w-full px-3 py-2 border border-[var(--border)] rounded-[8px] text-[12px] text-[var(--t900)] focus:outline-none focus:border-[var(--blue)] resize-none"
                />
                <div className="flex gap-2 justify-end">
                  <button onClick={() => { setEditNotes(false); setNotesVal(target.notes) }} className="px-3 py-1.5 text-[11px] font-semibold text-[var(--t500)] hover:bg-[var(--bg)] rounded-[6px] transition">{t.cancel}</button>
                  <button onClick={handleSaveNotes} className="px-3 py-1.5 text-[11px] font-semibold bg-[var(--blue)] text-white rounded-[6px] hover:bg-[var(--blue-h)] transition">{t.save}</button>
                </div>
              </div>
            ) : (
              <div className="text-[12px] text-[var(--t500)] leading-[1.6]">
                {target.notes || <span className="italic text-[var(--t300)]">{t.noNotes}</span>}
              </div>
            )}
          </div>

          {/* Delete */}
          <div className="pt-2 border-t border-[var(--border)] flex justify-end">
            <button
              onClick={handleDelete}
              className="text-[11px] font-semibold text-[var(--t300)] hover:text-[var(--red)] transition flex items-center gap-1"
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/><path d="M10 11v6M14 11v6"/><path d="M9 6V4h6v2"/>
              </svg>
              {t.removeUniversity}
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

// ── Main client ───────────────────────────────────────────────

export default function UniversityClient({ initialTargets, insights, programmeStats, userId, profileDefaults }: Props) {
  const [targets, setTargets] = useState<UniversityTarget[]>(initialTargets)
  const [showForm, setShowForm] = useState(false)
  const [view, setView] = useState<'targets' | 'compare'>('targets')
  const locale = useLocale()
  const t = T[locale]

  function handleAdd(u: UniversityTarget) {
    setTargets(prev => [u, ...prev])
    setShowForm(false)
  }

  function handleDelete(id: string) {
    setTargets(prev => prev.filter(t => t.id !== id))
  }

  function handleUpdate(id: string, patch: Partial<UniversityTarget>) {
    setTargets(prev => prev.map(t => t.id === id ? { ...t, ...patch } : t))
  }

  const byStatus = {
    offer:      targets.filter(t => t.status === 'offer' || t.status === 'enrolled'),
    applied:    targets.filter(t => t.status === 'applied'),
    researching: targets.filter(t => t.status === 'researching'),
    rejected:   targets.filter(t => t.status === 'rejected'),
  }

  return (
    <div className="flex flex-col min-h-screen">
      {/* Header */}
      <div className="bg-white border-b border-[var(--border)] px-9 h-14 flex items-center justify-between sticky top-0 z-50">
        <div>
          <div className="font-display font-bold text-[17px] text-[var(--t900)]">{t.pageTitle}</div>
          <div className="text-[11px] text-[var(--t500)] mt-0.5">{t.pageSubtitle(targets.length)}</div>
        </div>
        <button
          onClick={() => setShowForm(v => !v)}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-[8px] text-[12px] font-semibold bg-[var(--blue)] text-white hover:bg-[var(--blue-h)] transition"
        >
          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M12 5v14M5 12h14"/>
          </svg>
          {t.addUniversity}
        </button>
      </div>

      <div className="p-[28px_36px] flex-1">
        {/* View switch: 目标 tracker / 对比 official-data dashboard */}
        <div className="flex items-center gap-1 mb-5 border-b border-[var(--border)]">
          {([['targets', t.tabTargets], ['compare', t.tabCompare]] as const).map(([key, label]) => (
            <button key={key} onClick={() => setView(key)}
              className={`px-5 py-2.5 text-[13px] font-semibold border-b-2 -mb-[1px] transition-colors ${
                view === key ? 'border-[var(--blue)] text-[var(--blue)]' : 'border-transparent text-[var(--t500)] hover:text-[var(--t900)]'
              }`}>
              {label}
            </button>
          ))}
        </div>

        {view === 'compare' && (
          <CompareTab
            stats={programmeStats}
            onTargetAdded={t => {
              setTargets(prev => [{
                id: t.id, name: t.name, country: '', programme: t.programme,
                deadline: null, requirements: '', notes: '', status: 'researching',
                referenceLink: '', applicationPlan: null, planUpdatedAt: null,
              }, ...prev])
              setView('targets')
            }}
          />
        )}

        {view === 'targets' && (<>
        {/* Add form */}
        {showForm && <AddForm defaults={profileDefaults} onAdd={handleAdd} onCancel={() => setShowForm(false)} />}

        {/* Empty state */}
        {targets.length === 0 && !showForm && (
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <div className="text-[48px] mb-4">🎓</div>
            <div className="font-display font-bold text-[16px] text-[var(--t900)] mb-1">{t.emptyTitle}</div>
            <div className="text-[13px] text-[var(--t500)] mb-5">{t.emptyDesc}</div>
            <button onClick={() => setShowForm(true)} className="px-4 py-2 rounded-[8px] text-[13px] font-semibold bg-[var(--blue)] text-white hover:bg-[var(--blue-h)] transition">
              {t.addFirst}
            </button>
          </div>
        )}

        {/* Cards grouped by status */}
        {targets.length > 0 && (
          <div className="space-y-6">
            {byStatus.offer.length > 0 && (
              <section>
                <div className="text-[11px] font-bold text-[var(--t300)] uppercase tracking-widest mb-3">{t.secOffers}</div>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
                  {byStatus.offer.map(t => <UniversityCard key={t.id} target={t} insight={insights[t.id]} userId={userId} onDelete={handleDelete} onUpdate={handleUpdate} />)}
                </div>
              </section>
            )}
            {byStatus.applied.length > 0 && (
              <section>
                <div className="text-[11px] font-bold text-[var(--t300)] uppercase tracking-widest mb-3">{t.secApplied}</div>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
                  {byStatus.applied.map(t => <UniversityCard key={t.id} target={t} insight={insights[t.id]} userId={userId} onDelete={handleDelete} onUpdate={handleUpdate} />)}
                </div>
              </section>
            )}
            {byStatus.researching.length > 0 && (
              <section>
                <div className="text-[11px] font-bold text-[var(--t300)] uppercase tracking-widest mb-3">{t.secResearching}</div>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
                  {byStatus.researching.map(t => <UniversityCard key={t.id} target={t} insight={insights[t.id]} userId={userId} onDelete={handleDelete} onUpdate={handleUpdate} />)}
                </div>
              </section>
            )}
            {byStatus.rejected.length > 0 && (
              <section>
                <div className="text-[11px] font-bold text-[var(--t300)] uppercase tracking-widest mb-3">{t.secRejected}</div>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
                  {byStatus.rejected.map(t => <UniversityCard key={t.id} target={t} insight={insights[t.id]} userId={userId} onDelete={handleDelete} onUpdate={handleUpdate} />)}
                </div>
              </section>
            )}
          </div>
        )}
        </>)}
      </div>
    </div>
  )
}
